### ISSUE TITLE
Sometimes the hand is miss tracking

### ISSUE THREAD

**Issue by lesterleefat0418** [keijiro/BlazePalmBarracuda#2]
Will optimal the hand tracking in the future? Cause I see the hand sometimes are miss tracking in case of hand movement

**Comment by keijiro** [comment]
This is a straight port of the MediaPipe Palm, so the tracking quality depends on the original model. You can ask them (Google MediaPipe team) to improve it.

**Comment by keijiro** [comment]
I'm closing this issue now. Please feel free to reopen it for further problems.
