### ISSUE TITLE
IOS Test

### ISSUE THREAD

**Issue by andreobvio** [keijiro/BlazePalmBarracuda#3]
Hello! 

I am trying to import your project to an already existing project that I have, I could make it run if the platform target is macOs or Windows, but when I setup it up to IOS I am getting that shader problem. Can someone help me with that?

Thanks.
<img width="1090" alt="Screenshot 2023-02-09 at 12 11 55" src="https://user-images.githubusercontent.com/114940629/217852120-8e881a95-6021-4b60-9bfe-6782c9e8bdf6.png">

**Comment by keijiro** [comment]
It doesn't reproduce on my side. Please check if the BlazePalmBarracuda package has been imported via Package Manager.

**Comment by keijiro** [comment]
I close this issue now. Please reopen it for further problems.
